;cc #ifndef QS_BASE_CONST
;cc #define QS_BASE_CONST

;cc #ifndef QS_MAXPATH
QS_MAXPATH      equ     260                                     ;
;cc #endif
AF_ALIGN        equ     4096                                    ; AF i/o buffer size
AF_ALIGN_SECT   equ     8                                       ;
MAX_SECTOR_SIZE equ     4096                                    ; max supported sector size

;cc #endif // QS_BASE_CONST
